//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBDbContext : DbContext
    {
        public PBDbContext()
            : base("name=PBDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PingBiao_BiaoDuan> PingBiao_BiaoDuan { get; set; }
        public virtual DbSet<PingBiao_KaiBiaoTouBiao> PingBiao_KaiBiaoTouBiao { get; set; }
        public virtual DbSet<PingBiao_PW_LoginInfo> PingBiao_PW_LoginInfo { get; set; }
        public virtual DbSet<PingBiao_Pw_Mark> PingBiao_Pw_Mark { get; set; }
    }
}
