//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_TB_QingDanItem
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string QingDanNO { get; set; }
        public string QingDanName { get; set; }
        public Nullable<int> QingDanType { get; set; }
        public string XiangMuTZ { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ZongHeUnitPrice { get; set; }
        public Nullable<decimal> LaborUnitPrice { get; set; }
        public Nullable<decimal> MaterialUnitPrice { get; set; }
        public Nullable<decimal> MachineUnitPrice { get; set; }
        public Nullable<decimal> OverheadUnitPrice { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> RiskUnitPrice { get; set; }
        public Nullable<decimal> ZongHeTotalPrice { get; set; }
        public string Remark { get; set; }
        public string DanWeiGCNO { get; set; }
        public string DanWeiGCName { get; set; }
        public string DanWeiGuid { get; set; }
        public string DanWeiName { get; set; }
        public string Xh { get; set; }
        public Nullable<decimal> Zgj { get; set; }
        public string Gcnr { get; set; }
        public string Jsgz { get; set; }
        public Nullable<decimal> Zcf { get; set; }
        public Nullable<decimal> Fcf { get; set; }
        public Nullable<decimal> Zgr { get; set; }
        public string GCType { get; set; }
        public string Unit_OK { get; set; }
        public Nullable<decimal> Quantity_OK { get; set; }
        public Nullable<decimal> ZongHeTotalPrice_OK { get; set; }
        public Nullable<int> DuoQueX { get; set; }
        public Nullable<int> IS_Accord_TZ { get; set; }
        public Nullable<decimal> ZongHeUnitPrice_OK { get; set; }
        public Nullable<int> Is_Error_TZ { get; set; }
        public Nullable<int> ISBiaoDi { get; set; }
        public Nullable<decimal> EquipmentRate { get; set; }
        public Nullable<decimal> RestRate { get; set; }
        public Nullable<decimal> LawfeeRate { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string MainBQItem { get; set; }
        public Nullable<decimal> LimitedRate { get; set; }
        public Nullable<decimal> Zgj_OK { get; set; }
        public Nullable<decimal> LaborUnitPrice_OK { get; set; }
        public Nullable<decimal> MaterialUnitPrice_OK { get; set; }
        public Nullable<decimal> MachineUnitPrice_OK { get; set; }
        public Nullable<decimal> OverheadUnitPrice_OK { get; set; }
        public Nullable<decimal> Profit_OK { get; set; }
        public string TiaoZhengContent { get; set; }
        public string ISQuery { get; set; }
        public string QingDanName_OK { get; set; }
        public string XiangMuTZ_OK { get; set; }
        public string BaoJiaHLXMark { get; set; }
        public Nullable<decimal> Jjrg { get; set; }
        public string DanXiangNo { get; set; }
        public Nullable<decimal> DergfDj { get; set; }
        public Nullable<decimal> ZongHeFei { get; set; }
        public Nullable<decimal> DergfHj { get; set; }
        public string IsQDFX { get; set; }
        public string IsZongHeUnitPriceFX { get; set; }
        public Nullable<decimal> QuanZhong { get; set; }
        public string Xmbm { get; set; }
        public Nullable<decimal> Zjfqt { get; set; }
        public Nullable<decimal> Zjfqtfl { get; set; }
        public Nullable<decimal> Jjffl { get; set; }
        public string Js { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> Qtgcf { get; set; }
        public Nullable<decimal> Jjf { get; set; }
        public Nullable<decimal> Sj { get; set; }
        public string Iszg { get; set; }
        public string Djfx { get; set; }
        public string Parent_Qdbm { get; set; }
    }
}
