//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_KaiBiaoTouBiao
    {
        public string FileMiFeng { get; set; }
        public string GongQi { get; set; }
        public string BaoZhengJin { get; set; }
        public string TouBiaoTotal { get; set; }
        public string FaRenDb { get; set; }
        public string XiangMuJL { get; set; }
        public string Remark { get; set; }
        public string Zlcn { get; set; }
        public string QianShou { get; set; }
        public string ZhengShuYX { get; set; }
        public string IsSucceed { get; set; }
        public string UseToolName { get; set; }
        public string IsChuBuPS { get; set; }
        public string ZiShengPmName { get; set; }
        public string CBS_Code { get; set; }
        public string CBS_Name { get; set; }
        public string CBS_Date { get; set; }
        public string IsNextPass { get; set; }
        public string IsFeiBiao { get; set; }
        public string FeiBiaoReason { get; set; }
        public string AnBiaoNo { get; set; }
        public Nullable<int> AllPages { get; set; }
        public string PagesDetail { get; set; }
        public string FeiBiaoJD { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string DanWeiGuid { get; set; }
        public string DanWeiName { get; set; }
        public Nullable<System.DateTime> ComeTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public string IsAnShi { get; set; }
        public string UseToolVersion { get; set; }
        public string ZaoJiaRBH { get; set; }
        public string ZaoJiaRXM { get; set; }
        public string Dblx { get; set; }
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string ClientGuid { get; set; }
        public string IsJieMi { get; set; }
        public string ToolSoftName { get; set; }
        public string TBMacAddress { get; set; }
        public Nullable<System.DateTime> UPR_DATE { get; set; }
        public string TBIP { get; set; }
        public Nullable<System.DateTime> TBCreateDate { get; set; }
        public string TBMakeMacAddress { get; set; }
        public string TBFileGuid { get; set; }
        public string TBFileName { get; set; }
        public string IsChuBuPass { get; set; }
        public string TBFileAttchGuid { get; set; }
        public string TBFileAttachConnectionString { get; set; }
        public Nullable<int> TBImportPercent { get; set; }
        public string DigitalEnvelope { get; set; }
        public string IsPayForBzj { get; set; }
        public Nullable<System.DateTime> JiaoNaDate { get; set; }
        public Nullable<decimal> BzjMoney { get; set; }
        public string DecrTB { get; set; }
        public string DecrTB_UnitName { get; set; }
        public Nullable<System.DateTime> DecrTBJieMi_Date { get; set; }
        public string DecrZB_Name { get; set; }
        public Nullable<decimal> ChengXinFeng { get; set; }
        public string IsNeedSecondCheck { get; set; }
        public string DecrSK { get; set; }
        public Nullable<System.DateTime> DecrZB_Date { get; set; }
        public string DecrZB_UserGuid { get; set; }
        public string IsYouXiaoXingPass { get; set; }
        public string IsTechSucceed { get; set; }
        public string SuoNumber { get; set; }
        public string JiaoYanNumber { get; set; }
        public Nullable<System.DateTime> EndBiaoShuDate { get; set; }
        public Nullable<decimal> TbrRlv { get; set; }
        public string IsPFFinish { get; set; }
        public string IsTouBiao { get; set; }
        public string ZZJGDM { get; set; }
        public string QYDF { get; set; }
        public string XMJL { get; set; }
        public string XMJLDF { get; set; }
        public string Biaoduanno { get; set; }
        public string gongqiWB { get; set; }
        public string IsTechPass { get; set; }
        public string IsXYXPSPass { get; set; }
        public string IsZiGeYSPass { get; set; }
        public string IsXSPSPass { get; set; }
        public string IsBaoJiaHeLiXPFPass { get; set; }
        public string IsDlbjYouXiao { get; set; }
        public string DlxmbjWuXiaoReason { get; set; }
        public Nullable<System.DateTime> TuiHuiTime { get; set; }
        public string TuiHuiReason { get; set; }
        public string LianXiRen { get; set; }
        public string LiXiRenTel { get; set; }
        public string LiXiMobile { get; set; }
        public string IsCalculated { get; set; }
        public string TBFileDigitalSignal { get; set; }
        public string ZBREncryptPublicKey { get; set; }
        public string TBREncryptPublicKey { get; set; }
        public string TBRPublicKey { get; set; }
        public string FileGLGuid { get; set; }
        public string ZiShenZiLiao { get; set; }
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string B3 { get; set; }
        public string ISCanYuPb { get; set; }
        public string KaiBiaoReMark { get; set; }
        public string IsUseDisk { get; set; }
        public string BZJType { get; set; }
        public string CreateGuid { get; set; }
        public string ZiGeYSReason { get; set; }
        public string YouXXShenChaReason { get; set; }
        public string TechKBRemark { get; set; }
        public string DecrZX { get; set; }
        public string DecrZX_Name { get; set; }
        public string DecrZX_UserGuid { get; set; }
        public Nullable<System.DateTime> DecrZX_Date { get; set; }
        public string DecrTB_ZT { get; set; }
        public string DecrSK_ZT { get; set; }
        public string IsTechSucceedShow { get; set; }
        public string TBFileStorageData { get; set; }
        public string ZBRRemark { get; set; }
        public string XunBiao_Status { get; set; }
        public string IsEcoSucceed { get; set; }
    }
}
