//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_TB_RcjhzMx
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string DanWeiName { get; set; }
        public string DanWeiGuid { get; set; }
        public string DanWeiGCNO { get; set; }
        public string DanWeiGCName { get; set; }
        public Nullable<decimal> Ysj { get; set; }
        public Nullable<decimal> Dj { get; set; }
        public Nullable<decimal> Sl { get; set; }
        public Nullable<decimal> Hj { get; set; }
        public string RcjId { get; set; }
        public string RcjBm { get; set; }
        public string Mc { get; set; }
        public string Ggxh { get; set; }
        public string Dw { get; set; }
        public string Zbjxbz { get; set; }
        public string Jgbz { get; set; }
        public string Sbbz { get; set; }
        public string Wjjclbz { get; set; }
        public string Cd { get; set; }
        public string Gycs { get; set; }
        public string Bz { get; set; }
        public string Rcjlb { get; set; }
        public string Pblb { get; set; }
    }
}
