//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_BiaoDuanExt
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string KeyName { get; set; }
        public string Value { get; set; }
    }
}
