//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_TB_Csxm1Mx
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string Jsjc { get; set; }
        public Nullable<decimal> Fl { get; set; }
        public Nullable<decimal> Je { get; set; }
        public string Xmlb { get; set; }
        public string DanWeiGCNo { get; set; }
        public string DanWeiGCName { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public Nullable<decimal> Js { get; set; }
        public string DanWeiName { get; set; }
        public string DanWeiGuid { get; set; }
        public string ISBiaoDi { get; set; }
        public string ISMathErrCheckTZ { get; set; }
        public string DuoQueX { get; set; }
        public string GCType { get; set; }
        public string Mc_OK { get; set; }
        public Nullable<decimal> Je_OK { get; set; }
        public string ISValidCheckTZ { get; set; }
        public Nullable<decimal> fl_OK { get; set; }
        public Nullable<decimal> js_OK { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Jjrg { get; set; }
    }
}
