//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_ZB_CaiLiaoZGMX
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public string Ggxh { get; set; }
        public string Dw { get; set; }
        public Nullable<decimal> Sl { get; set; }
        public Nullable<decimal> Dj { get; set; }
        public Nullable<decimal> Hj { get; set; }
        public string Bz { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string DanWeiGCNO { get; set; }
        public string DanWeiGCName { get; set; }
        public string Clbh { get; set; }
        public string RcjId { get; set; }
        public string GCType { get; set; }
    }
}
