//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_Pw_Mark
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string DanWeiGuid { get; set; }
        public string PingWeiGuid { get; set; }
        public string PFDGuid { get; set; }
        public string MarkReason { get; set; }
        public string MarkLevel { get; set; }
        public string Bz { get; set; }
        public string XiuGaiData { get; set; }
        public Nullable<decimal> PingWeiMark { get; set; }
        public string PFDType { get; set; }
        public string DanWeiGcName { get; set; }
        public string DanWeiGcNO { get; set; }
        public string QingDanNo { get; set; }
        public string MarkReasonPic { get; set; }
    }
}
