//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_TB_MeasureItem
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string MeasureItemId { get; set; }
        public string OrderNum { get; set; }
        public string MeasureItemType { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ZongHeUnitPrice { get; set; }
        public Nullable<decimal> LaborUnitPrice { get; set; }
        public Nullable<decimal> MaterialUnitPrice { get; set; }
        public Nullable<decimal> MachineUnitPrice { get; set; }
        public Nullable<decimal> OverheadUnitPrice { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> RiskUnitPrice { get; set; }
        public Nullable<decimal> ZongHeTotalPrice { get; set; }
        public string DANWEIGCNO { get; set; }
        public string DanWeiGCName { get; set; }
        public string DanWeiGuid { get; set; }
        public string DanWeiName { get; set; }
        public Nullable<decimal> QuFeiJS { get; set; }
        public Nullable<decimal> FeiLv { get; set; }
        public string Gcnr { get; set; }
        public Nullable<decimal> Zcf { get; set; }
        public Nullable<decimal> Fcf { get; set; }
        public string Jsgz { get; set; }
        public string MeasureItemName { get; set; }
        public Nullable<decimal> Zgj { get; set; }
        public Nullable<decimal> Zgr { get; set; }
        public string Xmtz { get; set; }
        public string ISBiaoDi { get; set; }
        public Nullable<decimal> ZongHeUnitPrice_OK { get; set; }
        public Nullable<decimal> ZongHeTotalPrice_OK { get; set; }
        public string ISValidCheckTZ { get; set; }
        public string ISMathErrCheckTZ { get; set; }
        public string GCType { get; set; }
        public string DuoQueX { get; set; }
        public Nullable<decimal> Zgj_OK { get; set; }
        public Nullable<decimal> Quantity_OK { get; set; }
        public Nullable<decimal> LaborUnitPrice_OK { get; set; }
        public Nullable<decimal> MaterialUnitPrice_OK { get; set; }
        public Nullable<decimal> MachineUnitPrice_OK { get; set; }
        public Nullable<decimal> OverheadUnitPrice_OK { get; set; }
        public Nullable<decimal> Profit_OK { get; set; }
        public string TiaoZhengContent { get; set; }
        public string MeasureItemName_OK { get; set; }
        public Nullable<decimal> Jjrg { get; set; }
        public Nullable<decimal> DergfDj { get; set; }
        public Nullable<decimal> DergfHj { get; set; }
    }
}
