//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PingBiao_ZB_QingDanItem
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string QingDanNO { get; set; }
        public string QingDanName { get; set; }
        public string XiangMuTZ { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ZongheUnitPrice { get; set; }
        public Nullable<decimal> ZongheTotalPrice { get; set; }
        public string Remark { get; set; }
        public string QingDanType { get; set; }
        public string DANWEIGCNO { get; set; }
        public string DanWeiGCName { get; set; }
        public string GCType { get; set; }
        public string MainBQItem { get; set; }
        public Nullable<decimal> LimitedRate { get; set; }
        public string DanXiangNo { get; set; }
        public Nullable<decimal> zgj { get; set; }
        public Nullable<decimal> ZongHeFei { get; set; }
        public Nullable<decimal> DergfDj { get; set; }
        public Nullable<decimal> DergfHj { get; set; }
        public string IsZongHeUnitPriceFX { get; set; }
        public Nullable<decimal> QuanZhong { get; set; }
        public string Xmbm { get; set; }
        public string Js { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public string Iszg { get; set; }
        public string Djfx { get; set; }
        public string Parent_Qdbm { get; set; }
        public string Gcnr { get; set; }
    }
}
