//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_TB_FywjMx
    {
        public Nullable<decimal> zgj_OK { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public Nullable<decimal> Je { get; set; }
        public Nullable<decimal> Zgj { get; set; }
        public string Fyxlb { get; set; }
        public string DanWeiGCName { get; set; }
        public string DanWeiGCNO { get; set; }
        public string DanWeiName { get; set; }
        public string DanWeiGuid { get; set; }
        public string Zjbz { get; set; }
        public string CostCode { get; set; }
        public string Parent_No { get; set; }
        public string SummaryFlag { get; set; }
        public Nullable<decimal> Je_OK { get; set; }
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
    }
}
