//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using Epoint.Framework.Contract;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PingBiao_BiaoDuan 
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        [Key]
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string BiaoDuanNo { get; set; }
        public string BiaoDuanName { get; set; }
        public string JianSheDanWei { get; set; }
        public string DaiLiName { get; set; }
        public string IsAllowLHT { get; set; }
        public string SoftCode { get; set; }
        public string Version { get; set; }
        public string IsXYXPS_TechEnd { get; set; }
        public string IsFBTKPSEnd { get; set; }
        public string JiemiMiute { get; set; }
        public string IsBJHLXPFHZ { get; set; }
        public string IsZiGeYSEnd { get; set; }
        public Nullable<decimal> TuiJianPwFzrNo { get; set; }
        public string IsBaoJiaHeLiXPFEnd { get; set; }
        public string IsQiTaEnd { get; set; }
        public string IsQiTaHZ { get; set; }
        public Nullable<System.DateTime> PingBiaoDate { get; set; }
        public string IsChuBuPSEnd { get; set; }
        public string PingBiaoIsStart { get; set; }
        public string IsZHBHZ { get; set; }
        public string ZhaoBiaoFW { get; set; }
        public string GongZuoRY { get; set; }
        public string YiChangQK { get; set; }
        public string PingBiaoAdress { get; set; }
        public Nullable<int> IsZhengFuTouZi { get; set; }
        public string ZBR_Guid { get; set; }
        public string ZBR_UnitName { get; set; }
        public string IsZongHeBiaoEnd { get; set; }
        public string IsXSPSEnd { get; set; }
        public string IsXYXPSEnd { get; set; }
        public string IsTechEnd { get; set; }
        public string YuDingGuid { get; set; }
        public string IsValidCheckEnd { get; set; }
        public Nullable<System.DateTime> allowJieMiData { get; set; }
        public string KaiBiaoAddress { get; set; }
        public string KaiBiaoTime { get; set; }
        public string BeiZhu { get; set; }
        public string JBR_Guid { get; set; }
        public string JBR_Name { get; set; }
        public Nullable<System.DateTime> KaiBiaoDate { get; set; }
        public string PingBiaoIsEnd { get; set; }
        public string ZhaoBiaoR { get; set; }
        public Nullable<int> Jhgq { get; set; }
        public string Zlyq { get; set; }
        public Nullable<int> IsAllZhengFuTouzi { get; set; }
        public Nullable<int> IsUseYCPingBiao { get; set; }
        public string IsBiaoJiaBJB { get; set; }
        public string IsTouBiaoJGFX { get; set; }
        public string IsQingDanFX { get; set; }
        public string IsCuoShiXMFX { get; set; }
        public string IsEcoFX { get; set; }
        public string IsQuFeiCheck { get; set; }
        public string IsQingDanFHXJC { get; set; }
        public string IsCuoShiFHXJC { get; set; }
        public string IsQiTaFHXJC { get; set; }
        public string IsCuoShiXMHXFX { get; set; }
        public string IsDXGCFX { get; set; }
        public string KaiBiaoR_Guid { get; set; }
        public string KaiBiaoR_Name { get; set; }
        public string JianGuanRYDL1 { get; set; }
        public string JianGuanRYDL2 { get; set; }
        public string IsMathErrCheck { get; set; }
        public string IsEcoEnd { get; set; }
        public string IsMathErrCheck_New { get; set; }
        public string GongChengXingZhi { get; set; }
        public Nullable<System.DateTime> JunGongShiJian { get; set; }
        public Nullable<System.DateTime> KaiGongShiJian { get; set; }
        public string CengShu { get; set; }
        public string JianSheGuiMo { get; set; }
        public string JianZhuJieGou { get; set; }
        public string HistoryDB_Name { get; set; }
        public Nullable<int> If_Moved { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string IsNiDingQuestion { get; set; }
        public string IsDoBiaoJiaoBJB { get; set; }
        public string ZBFileAttchGuid { get; set; }
        public string ZBFileAttachConnectionString { get; set; }
        public string IsChangBiao { get; set; }
        public Nullable<int> IsChongPing { get; set; }
        public string PingBiaoBF { get; set; }
        public string FanBenNo { get; set; }
        public Nullable<System.DateTime> QingBiaoTime { get; set; }
        public Nullable<int> QingBiaoDWNum { get; set; }
        public string BDFileAttachGuid { get; set; }
        public string BDFileAttachConnectionString { get; set; }
        public Nullable<int> PingBiaoDWNum { get; set; }
        public string DecrZB_UserGuid { get; set; }
        public string DecrZB_Name { get; set; }
        public Nullable<System.DateTime> DecrZB_date { get; set; }
        public string DecrZB_UnitName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string QingBiaoBGAttachGuid { get; set; }
        public string PingBiaoBGAttachGuid { get; set; }
        public Nullable<decimal> ControlPrice { get; set; }
        public string DaiLiGuid { get; set; }
        public string IsPause { get; set; }
        public string IsNeedSecondEnvelope { get; set; }
        public string domain { get; set; }
        public string PingBiaoBGConnectionString { get; set; }
        public string QingBiaoBGConnectionString { get; set; }
        public Nullable<int> FeiBiaoRound { get; set; }
        public string IsDlxmFHXJC { get; set; }
        public string SysXiaQuCode { get; set; }
        public string K1 { get; set; }
        public string Q1 { get; set; }
        public string ZbXmGuid { get; set; }
        public string PingBiaoEndOperator { get; set; }
        public string QingBiaoIsEnd { get; set; }
        public string QingBiaoOperator { get; set; }
        public Nullable<System.DateTime> KaiBiaoEndTime { get; set; }
        public string KaiBiaoEndOperator { get; set; }
        public string toubiaoXS { get; set; }
        public string PBYiChangQK { get; set; }
        public string KBAttachGuid { get; set; }
        public string KBConnectionString { get; set; }
        public Nullable<int> BaoJiaRound { get; set; }
        public string XiaQuCode { get; set; }
        public string IsKaiBiaoEnd { get; set; }
        public string IsFromWeb { get; set; }
        public string PingBiaoAddress { get; set; }
        public string IsTongBu { get; set; }
        public string ALLowFZRIsJiaFang { get; set; }
        public string KBGZY_Guid { get; set; }
        public string KBGZY_Name { get; set; }
        public string QingDanBAAttachGuid { get; set; }
        public string QingDanBAConnectionString { get; set; }
        public string PackageStatus { get; set; }
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string IsZhongHeFX { get; set; }
        public string EcoKBIsEnd { get; set; }
        public string IsYouXXShenChaEnd { get; set; }
        public string FuYiBiaoDuanGuid { get; set; }
        public string FuYiNum { get; set; }
        public string ISFBPBDone { get; set; }
        public string ZBFileStorageDate { get; set; }
        public string DYFileStorageDate { get; set; }
        public string BDFileStorageDate { get; set; }
        public Nullable<System.DateTime> PingBiaoEndDate { get; set; }
        public string IsOnReadingKBJL { get; set; }
        public string IsOpenYingJi { get; set; }
        public string IsKaiBiaoEnd_Ready { get; set; }
        public string IsXunBiaoEnd { get; set; }
        public Nullable<System.DateTime> XunBiaoEndDate { get; set; }
        public string XunBiaoEndOperator { get; set; }
        public string IsLiuBiao { get; set; }
    }
}
