//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_ZhiXun
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string BiaoDuanNo { get; set; }
        public string BiaoDuanName { get; set; }
        public string SenderCode { get; set; }
        public string SenderName { get; set; }
        public Nullable<System.DateTime> SenderDate { get; set; }
        public string DanWeiGuid { get; set; }
        public string HuiDaContent { get; set; }
        public string HuiDaCoder { get; set; }
        public string HuiDaName { get; set; }
        public Nullable<System.DateTime> HuiDaDate { get; set; }
        public string ZhiZunNo { get; set; }
        public string DanWeiName { get; set; }
        public string HuiDaLimit { get; set; }
        public string DS { get; set; }
        public string Cert { get; set; }
        public string ZhiYiTitle { get; set; }
        public string ZhiYiContent { get; set; }
        public string PBWYHHeaderContent { get; set; }
        public Nullable<System.DateTime> HuiDaLimitTime { get; set; }
        public string PBWYHContent { get; set; }
        public string Ispass { get; set; }
        public string HuiFuYQ { get; set; }
        public string AttachConnStr { get; set; }
        public string IsQZ { get; set; }
        public string DaFuAttachGuid { get; set; }
        public string FilePath { get; set; }
    }
}
