//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_PW_LoginInfo
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string Pw_Type { get; set; }
        public string PW_Zy { get; set; }
        public string IsZhongHePw { get; set; }
        public string IsNeedHuiBi { get; set; }
        public string HuiBiReason { get; set; }
        public string ChuBuPingShenYiJian { get; set; }
        public string CANumber { get; set; }
        public string MechineNo { get; set; }
        public string IsEcoEnd { get; set; }
        public Nullable<System.DateTime> Pw_Birthday { get; set; }
        public string Pw_ZhiCheng { get; set; }
        public Nullable<System.DateTime> Pw_RuKuDate { get; set; }
        public string IsXYXPS_TechEnd { get; set; }
        public string IsFBTKPSEnd { get; set; }
        public string IsXYXPSEnd { get; set; }
        public string IsTechEnd { get; set; }
        public string IsTuiJianFZR { get; set; }
        public string IsBaoJiaHeLiXPFEnd { get; set; }
        public string ChuBuPSECQR { get; set; }
        public string IsChuBuPSEnd { get; set; }
        public string IsQiTaEnd { get; set; }
        public string IDNumber { get; set; }
        public string IsZongHeBiaoEnd { get; set; }
        public string IsPingJiaZBFilePass { get; set; }
        public string PingJiaZBFile { get; set; }
        public string IsZiGeYSEND { get; set; }
        public string IsValidCheckEnd { get; set; }
        public string IsXSPSEnd { get; set; }
        public string Pw_Guid { get; set; }
        public string Pw_Name { get; set; }
        public string Company { get; set; }
        public string PW_LoginID { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string IsLogin { get; set; }
        public string IsPingFenEnd { get; set; }
        public Nullable<System.DateTime> PingFenEndDate { get; set; }
        public string Area { get; set; }
        public string PW_Password { get; set; }
        public Nullable<System.DateTime> KaiBiaoDate { get; set; }
        public string CAKey { get; set; }
        public string CAGuid { get; set; }
        public string CAName { get; set; }
        public string CardNo { get; set; }
        public string MacAddress { get; set; }
        public string IsYuanChenPW { get; set; }
        public string photo_ContentType { get; set; }
        public string photo_FileName { get; set; }
        public byte[] photo { get; set; }
        public string IsCanYuZGSC { get; set; }
        public string IsYouXXShenChaEnd { get; set; }
        public Nullable<decimal> Exam_Mark { get; set; }
        public string Pw_Place { get; set; }
        public string Biaoduanno { get; set; }
        public string DLPW_type { get; set; }
        public string PBTimes { get; set; }
        public string IP { get; set; }
        public string PWYJ { get; set; }
        public string IsUploadFile { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
