//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.PingBiao.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Epoint.PingBiao.Contract;
    using Epoint.Framework.DAL;
    using Epoint.Core.Config;
    using Epoint.Core.Log;
    
    public partial class PBDbContext : DbContextBase
    {
        public PBDbContext()
            : base(CachedConfigContext.Current.DaoConfig.PB, new LogDbContext())
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    Database.SetInitializer<PBDbContext>(null);
        //    base.OnModelCreating(modelBuilder);
        //}
    
        public virtual DbSet<PingBiao_BiaoDuan> PingBiao_BiaoDuan { get; set; }
        public virtual DbSet<PingBiao_BiaoDuanExt> PingBiao_BiaoDuanExt { get; set; }
        public virtual DbSet<PingBiao_BuZhouBack> PingBiao_BuZhouBack { get; set; }
        public virtual DbSet<PingBiao_Eval_BaojiaMark> PingBiao_Eval_BaojiaMark { get; set; }
        public virtual DbSet<PingBiao_Eval_BiaoJiaBJB> PingBiao_Eval_BiaoJiaBJB { get; set; }
        public virtual DbSet<PingBiao_Eval_LastMark> PingBiao_Eval_LastMark { get; set; }
        public virtual DbSet<PingBiao_Eval_MeasureItem> PingBiao_Eval_MeasureItem { get; set; }
        public virtual DbSet<PingBiao_Eval_PingBiaoBF> PingBiao_Eval_PingBiaoBF { get; set; }
        public virtual DbSet<PingBiao_KaiBiaoTouBiao> PingBiao_KaiBiaoTouBiao { get; set; }
        public virtual DbSet<PingBiao_PW_LoginInfo> PingBiao_PW_LoginInfo { get; set; }
        public virtual DbSet<PingBiao_Pw_Mark> PingBiao_Pw_Mark { get; set; }
        public virtual DbSet<PingBiao_TB_Csxm1Mx> PingBiao_TB_Csxm1Mx { get; set; }
        public virtual DbSet<PingBiao_TB_FywjMx> PingBiao_TB_FywjMx { get; set; }
        public virtual DbSet<PingBiao_TB_MeasureItem> PingBiao_TB_MeasureItem { get; set; }
        public virtual DbSet<PingBiao_TB_OtherItem> PingBiao_TB_OtherItem { get; set; }
        public virtual DbSet<PingBiao_TB_QingDanItem> PingBiao_TB_QingDanItem { get; set; }
        public virtual DbSet<PingBiao_TB_RcjhzMx> PingBiao_TB_RcjhzMx { get; set; }
        public virtual DbSet<PingBiao_TBInfoMx> PingBiao_TBInfoMx { get; set; }
        public virtual DbSet<PingBiao_ZB_CaiLiaoZGMX> PingBiao_ZB_CaiLiaoZGMX { get; set; }
        public virtual DbSet<PingBiao_ZB_MeasureItem> PingBiao_ZB_MeasureItem { get; set; }
        public virtual DbSet<PingBiao_ZB_OtherItem> PingBiao_ZB_OtherItem { get; set; }
        public virtual DbSet<PingBiao_ZB_QingDanItem> PingBiao_ZB_QingDanItem { get; set; }
        public virtual DbSet<PingBiao_ZB_RcjhzMx_> PingBiao_ZB_RcjhzMx_ { get; set; }
        public virtual DbSet<PingBiao_ZhiXun> PingBiao_ZhiXun { get; set; }
    }
}
